### ISSUE TITLE
how can i change the pdf file font size?

### ISSUE THREAD

**Issue by ghost** [twtrubiks/python-pdfkit-example#1]
@twtrubiks 
i use the code 
`stream = pdfkit.from_string(input=html, output_path=False, options=options)`
in python to get a file stream, but the result is not satisfy, it`s font is too small, however it show nomal in html file,
now, how can i slove this problem?

**Comment by twtrubiks** [comment]
hi~  
I changed the font size from html, but sometimes it might fail

**Comment by ghost** [comment]
@twtrubiks 
i sloved it with changing the system default font size,
thank you all the same, best wish to you

**Comment by twtrubiks** [comment]
Thank you for providing a solution
